#!/bin/bash
# Télécharge une fois pour toutes les photos produits dans le dossier images/
# Usage : bash telecharger-images.sh
mkdir -p images
UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
ok=0; ko=0
get() {
  if [ -s "images/$1" ]; then ok=$((ok+1)); return; fi
  if curl -fsSL --retry 2 -m 60 -A "$UA" -o "images/$1" "$2" && file "images/$1" | grep -qiE 'image|bitmap'; then
    ok=$((ok+1)); echo "OK      $1"
  else
    rm -f "images/$1"; ko=$((ko+1)); echo "ECHEC   $1"
  fi
  sleep 0.3
}
get 'iphone-xr.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-xr-1.jpg'
get 'iphone-xs-max.jpg' 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-xs-max-new1.jpg'
get 'iphone-11.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-11-1.jpg'
get 'iphone-11-pro.jpg' 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-11-pro.jpg'
get 'iphone-11-pro-max.jpg' 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-11-pro-max-.jpg'
get 'iphone-12.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-2.jpg'
get 'iphone-12-pro.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-pro-2.jpg'
get 'iphone-12-pro-max.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-pro-max-2.jpg'
get 'iphone-13.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-2.jpg'
get 'iphone-13-pro.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-pro-2.jpg'
get 'iphone-13-pro-max.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-pro-max-2.jpg'
get 'iphone-14.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-1.jpg'
get 'iphone-14-pro.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-1.jpg'
get 'iphone-14-pro-max.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg'
get 'iphone-15.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-1.jpg'
get 'iphone-15-plus.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-plus-1.jpg'
get 'iphone-15-pro.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-pro-1.jpg'
get 'iphone-15-pro-max.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-pro-max-1.jpg'
get 'iphone-16.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-16-1.jpg'
get 'iphone-16-plus.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-16-plus-1.jpg'
get 'iphone-16-pro.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-16-pro-1.jpg'
get 'iphone-16-pro-max.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-16-pro-max-1.jpg'
get 'iphone-17.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-17-1.jpg'
get 'iphone-17-pro.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-17-pro-1.jpg'
get 'iphone-17-pro-max.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-17-pro-max-1.jpg'
get 'iphone-17-air.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-air-1.jpg'
get 'samsung-a07.jpg' 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a07-2.jpg'
get 'samsung-a16.jpg' 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a16-5g-1.jpg'
get 'samsung-a17.jpg' 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a17-4g-1.jpg'
get 'samsung-a26.jpg' 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a26-1.jpg'
get 'samsung-a56.jpg' 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a56-1.jpg'
get 'samsung-s22.jpg' 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-ultra-5g-1.jpg'
get 'samsung-s23.jpg' 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s23-ultra-5g-1.jpg'
get 'samsung-s24.jpg' 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-ultra-5g-sm-s928-1.jpg'
get 'samsung-s25.jpg' 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s25-ultra-sm-s938-1.jpg'
get 'samsung-s26.jpg' 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s26-ultra-1.jpg'
get 'samsung-z-fold-6.jpg' 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-z-fold6-1.jpg'
get 'pixel-9-pro-xl.jpg' 'https://fdn2.gsmarena.com/vv/pics/google/google-pixel-9-pro-xl-1.jpg'
get 'nokia-105.jpg' 'https://fdn2.gsmarena.com/vv/pics/nokia/nokia-105-2023-1.jpg'
get 'ipad-10e.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-10-2022-1.jpg'
get 'ipad-pro-m1.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-129-2021-1.jpg'
get 'ipad-pro-m2.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-129-2022-1.jpg'
get 'ipad-pro-m4.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-11-2024-2.jpg'
get 'ipad-air-m1.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-air-2022-1.jpg'
get 'ipad-air-m2.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-air-11-2024-2.jpg'
get 'macbook-pro-m1.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-spacegray-select-202011?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'macbook-pro-m2.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-spacegray-select-202206?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'macbook-pro-m3.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp14-spacegray-select-202310?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'macbook-pro-m4.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp14-spaceblack-select-202410?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'macbook-air-m1.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-space-gray-select-201810?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'macbook-air-m2.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-midnight-select-20220606?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'macbook-air-m3.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba13-midnight-select-202402?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'macbook-air-m4.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba13-skyblue-select-202503?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'airpod-max.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-max-select-202409-midnight?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'airpod-3.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MME73?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'airpod-4.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-4-anc-select-202409?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'airpod-pro.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-pro-3-hero-select-202509?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'ecouteur-iphone-lightning.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MMTN2?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'ecouteur-usb-c.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MTJY3?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'chargeur-complet.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MHJE3?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'cable-type-usb-c.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQKJ3?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'cable-iphone-lightning.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MM0A3?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'coque-iphone.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MA7E4?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'coque-ipad.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MWK63?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'bracelet-apple-watch.jpg' 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MYJ93?wid=800&hei=800&fmt=jpeg&qlt=90'
get 'apple-watch-serie-8.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-watch-8-1.jpg'
get 'apple-watch-serie-9.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-watch-series9-1.jpg'
get 'apple-watch-serie-10.jpg' 'https://fdn2.gsmarena.com/vv/pics/apple/apple-watch-series10-1.jpg'
get 'ps5-slim.jpg' 'https://gmedia.playstation.com/is/image/SIEPDC/ps5-product-thumbnail-01-en-14sep21?$800px--t$'
get 'ps5-pro.jpg' 'https://gmedia.playstation.com/is/image/SIEPDC/ps5-pro-dualsense-image-block-01-en-16aug24?$800px--t$'
get 'manette-ps5.jpg' 'https://gmedia.playstation.com/is/image/SIEPDC/dualsense-controller-product-thumbnail-01-en-14sep21?$800px--t$'
get 'dji-osmo.png' 'https://se-cdn.djiits.com/tpc/uploads/spu/cover/35d158a1f3d1a3a48ec4cf2220cfc426@small.png'
get 'dji-osmo-pocket3-combo.png' 'https://se-cdn.djiits.com/tpc/uploads/spu/cover/1d3aead32b2f5d1be8c083c27ba13c49@small.png'
get 'ray-ban-meta.jpg' 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/Ray-Ban_Stories.jpg/960px-Ray-Ban_Stories.jpg'
get 'jbl.png' 'https://fr.jbl.com/dw/image/v2/BFND_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw4e91d6eb/1_JBL_FLIP6_HERO_BLACK_29391_x2.png'
get 'laboubou.jpg' 'https://upload.wikimedia.org/wikipedia/en/a/a9/Pop_Mart_Labubu_The_Monsters_Exciting_Macaron.jpg'
get 'fifa24.jpg' 'https://upload.wikimedia.org/wikipedia/en/b/b3/EA_FC24_Cover.jpg'
get 'fifa25.jpg' 'https://upload.wikimedia.org/wikipedia/en/0/09/EA_FC_25_Cover.jpg'
get 'fifa26.png' 'https://upload.wikimedia.org/wikipedia/en/2/2f/FC_26_Cover.png'
get 'playstation-portal.jpg' 'https://gmedia.playstation.com/is/image/SIEPDC/ps-portal-remote-player-keyart-01-en-18aug23?$800px--t$'
get 'incassable.png' 'https://upload.wikimedia.org/wikipedia/commons/9/94/Screen_protector.png'
get 'prise-simple.jpg' 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/French-power-socket.jpg/960px-French-power-socket.jpg'
get 'connecteur-bnc.jpg' 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b9/BNC_connector_50_ohm_male.jpg/960px-BNC_connector_50_ohm_male.jpg'
echo
echo "Terminé : $ok images présentes, $ko échecs."
